{% set name = "sphinxcontrib-websupport" %}
{% set version = "1.2.4" %}
{% set sha256 = "4edf0223a0685a7c485ae5a156b6f529ba1ee481a1417817935b20bde1956232" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - sphinx
    - sphinxcontrib-serializinghtml

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.serializinghtml
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.python.org/pypi/sphinxcontrib-websupport
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx API for Web Apps
  description: |
    sphinxcontrib-websupport provides a Python API to easily integrate
    Sphinx documentation into your Web application
  doc_url: http://www.sphinx-doc.org/en/stable/
  dev_url: https://github.com/sphinx-doc/sphinxcontrib-websupport

extra:
  recipe-maintainers:
    - chohner
